name: Get Telegram Chat ID

on:
  workflow_dispatch:

jobs:
  get-chat-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python get_chat_id.py
